spring.application.name=EmployeeEvaluationSystem
server.port=${PORT:8484}
# db.properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.1.1.251:5432/TEST-DB
spring.datasource.username=postgres
spring.datasource.password=qwerty

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

# Disable runtime schema mutation to avoid startup failure
spring.jpa.hibernate.ddl-auto=none

application.security.jwt.secret-key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000


springdoc.api-docs.enabled=true      
# Enable OpenAPI documentation
springdoc.swagger-ui.enabled=true   
# Enable Swagger UI
springdoc.api-docs.path=v3/api-docs
# Path for the OpenAPI JSON
springdoc.swagger-ui.path=/swagger-ui.html
# Path for Swagger UI

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

# Enable SQL logging
spring.jpa.show-sql=true

# Format the SQL output for better readability
spring.jpa.properties.hibernate.format_sql=true

# Log the parameters bound to the query
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE


spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/tmp

